# Generated by Django 3.2.4 on 2021-06-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversariante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('setor', models.CharField(max_length=20, null=True)),
                ('datanascimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7)),
                ('foto', models.ImageField(blank=True, upload_to='nome/%d/%m/%Y/')),
            ],
            options={
                'ordering': ('datanascimento',),
            },
        ),
    ]
