# Generated by Django 3.2.4 on 2021-06-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniversario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniversariante',
            name='local',
            field=models.CharField(choices=[('bh', 'Belo Horizonte'), ('op', 'Ouro Preto'), ('ip', 'Ipatinga'), ('mc', 'Montes Claros'), ('jf', 'Juiz de Fora'), ('vg', 'Varginha')], default='bh', max_length=2),
        ),
    ]
